### User
POST http://172.16.100.248:60293/users
Content-Type: application/json

{
  "email" : "seok@gmail.com",
  "password" : "1234",
  "name" : "seok"
}

### User
POST http://172.16.100.248:60293/login
Content-Type: application/json

{
  "email" : "seok@gmail.com",
  "password" : "1234"
}



### Users 등록
POST http://localhost:8000/user-service/users
Content-Type: application/json

{
  "email" : "seok@gmail.com",
  "password" : "1234",
  "name" : "seok"
}

### User Login
POST http://localhost:8000/user-service/login
Content-Type: application/json

{
  "email" : "seok@gmail.com",
  "password" : "1234"
}


### GET USER (ORDERS)
GET http://localhost:8000/user-service/users/3b9877f6-cb57-4801-b1e3-19bc61025fa2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzYjk4NzdmNi1jYjU3LTQ4MDEtYjFlMy0xOWJjNjEwMjVmYTIiLCJleHAiOjE2MzAwNjA1MTZ9.lbflmq-0bVLUgZM-hz5tkzWboX-rhmbLvfhJt9XMhGKcHGYC8FgO_prfXW1rVYJCRfcjX2cifj9sjsRcYUyj8g
